/**
 * build-study.mjs: write the dated corpus study from corpus/results.json.
 *
 *   node scripts/build-study.mjs
 *
 * Deterministic and offline. Everything in the study folder except
 * first-run-results.json is generated here, so no figure in it is typed:
 *
 *   results.json          a copy of corpus/results.json as observed
 *   report-machine.html   the plain About page, annotated
 *   report-human.html     the Twain passage, annotated
 *   README.md             the table, the evasion comparison, localisation,
 *                         and every cell that moved between the first run
 *                         and this one, because the rules were revised after
 *                         the first run and a reader is owed the difference
 *
 * first-run-results.json is the one hand-kept file: the output of the very
 * first `tells corpus`, saved before any rule was touched.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { analyze } from '../src/report.mjs';
import { render } from '../src/render.mjs';
import { corpusTable, corpusLegend, evasionSummary, SHORT } from '../src/corpus.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const results = JSON.parse(readFileSync(join(ROOT, 'corpus', 'results.json'), 'utf8'));
const manifest = JSON.parse(readFileSync(join(ROOT, 'corpus', 'MANIFEST.json'), 'utf8'));
const DATE = results.observedAt;
const DIR = join(ROOT, 'studies', `${DATE}-corpus`);

function renderOne(id, out, caption) {
  const entry = manifest.files.find((f) => f.id === id);
  const text = readFileSync(join(ROOT, 'corpus', entry.path), 'utf8');
  const path = `corpus/${entry.path}`;
  const command = `tells render ${path}${entry.plain ? ' --plain' : ''}`;
  const report = analyze(text, { path, plain: !!entry.plain, observedAt: `${DATE}T00:00:00.000Z`, command });
  writeFileSync(join(DIR, out), render(report, text, { title: entry.title, caption }));
  return { out, entry, findings: report.totals.findings, words: report.document.words, command };
}

function movedCells(first, final) {
  const rows = [];
  for (const f of final.files) {
    const before = first.files.find((x) => x.id === f.id);
    if (!before) continue;
    for (const id of final.ruleIds) {
      const a = before.rates[id]?.count;
      const b = f.rates[id].count;
      if (a !== b) rows.push(`| ${f.id} | ${f.kind} | ${SHORT[id]} | ${a} | ${b} |`);
    }
  }
  return rows;
}

writeFileSync(join(DIR, 'results.json'), `${JSON.stringify(results, null, 2)}\n`);
const machine = renderOne('about-us', 'report-machine.html', `Written by ${manifest.files.find((f) => f.id === 'about-us').model} on ${DATE} for this corpus; prompt in corpus/MANIFEST.json.`);
const human = renderOne('twain-german', 'report-human.html', 'Mark Twain, 1880. Project Gutenberg eBook #119. Public domain in the United States.');

const firstPath = join(DIR, 'first-run-results.json');
const first = existsSync(firstPath) ? JSON.parse(readFileSync(firstPath, 'utf8')) : null;
const moved = first ? movedCells(first, results) : [];

const hybrids = results.files.filter((f) => f.localisation).map((f) => {
  const l = f.localisation;
  return `- \`${f.id}\`: lines ${l.machineLines[0]}-${l.machineLines[1]} are the inserted machine paragraph. They hold ${l.wordsInside} of ${l.wordsTotal} words (${(l.shareOfWords * 100).toFixed(1)}%) and ${l.findingsInside} of ${l.findingsTotal} findings (${(l.shareOfFindings * 100).toFixed(1)}%).`;
});

const readme = `# Corpus study, observed ${DATE}

Generated by \`node scripts/build-study.mjs\` from \`corpus/results.json\`. Nothing in this file is typed by hand.

${results.files.length} files of known origin, run through tells ${results.tool.version} with every rule turned on, including the ones that are off by default, because this table is the evidence for which rules separate anything. Provenance of every file, and the verbatim prompt of every machine text, is in \`corpus/MANIFEST.json\`.

## Rates

${corpusTable(results)}

${corpusLegend(results)}

${results.caveat}

## Evasion

${evasionSummary(results)}

The evasion sample is machine text, and the rules find almost nothing in it. That is the result: these rules count surface habits, and a writer or a model that avoids the habits is not counted. The author of the evasion sample had read the full rule list, so this is a best case for evasion.

## Localisation in the hybrid files

${hybrids.join('\n')}

## The rules were revised after the first run, and one was demoted after review

The rates above are in-sample. The first \`tells corpus\` run is kept unedited in \`first-run-results.json\`. Reading its findings showed detection bugs, the rules were fixed, and the corpus was run again. No corpus text was changed. What was fixed, and which way it moved the numbers:

- \`rule-of-three\` matched clause boundaries such as "on the other side, as was wished and expected". It now rejects clause openers, place names and introductory phrases. This lowered the human rows. It also stopped skipping sentences that contain a figure like 1,400. In the evasion sample that swapped one false finding for a real triad the first run had missed, so its count is 1 in both runs.
- \`negative-parallelism\` now prefers the full "is not just X, it is Y" frame over the bare "is not just", and accepts "merely" and "simply". This raised one machine row.
- \`em-dash\` was changed before the first run, after reading the fetched source files: it counts a double hyphen set tight between words, because the Gutenberg transcription of Twain writes every dash that way.

${moved.length} cells changed between the first run and this one (counts, not rates):

| file | kind | rule | first run | this run |
|---|---|---|---:|---:|
${moved.join('\n')}

After a hostile review in September 2026, \`rule-of-three\` was taken out of the
default set (\`--include rule-of-three\` turns it back on) and its reported span
was widened to cover all three members or report nothing. The reasons are in
the rule's own description and in the table above: its top human rate reaches
the machine rate, so it separates nothing here, and out of sample it produced
nine of the twelve findings across eight human passages. No corpus text was
changed for that decision either, and the rule's row is still in this table.

## Rendered reports

- [report-machine.html](report-machine.html): ${machine.entry.title}. ${machine.findings} findings in ${machine.words} words. \`${machine.command}\`
- [report-human.html](report-human.html): ${human.entry.title}. ${human.findings} findings in ${human.words} words. \`${human.command}\`

## Reproduce

\`\`\`
${results.command}
node scripts/build-study.mjs
\`\`\`
`;
writeFileSync(join(DIR, 'README.md'), readme);
console.log(`wrote studies/${DATE}-corpus: results.json, report-machine.html, report-human.html, README.md (${moved.length} cells moved since the first run)`);
