/**
 * studies-index.mjs: generate studies/INDEX.md from the study folders.
 *
 *   node scripts/studies-index.mjs
 *
 * Deterministic. A study is a folder named YYYY-MM-DD-<slug> holding a
 * results.json. The index states the observation date of each, never
 * "current": these are dated runs, and a re-run on another day is a new study.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = join(fileURLToPath(new URL('..', import.meta.url)), 'studies');

const rows = readdirSync(DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory() && /^\d{4}-\d{2}-\d{2}-/.test(e.name) && existsSync(join(DIR, e.name, 'results.json')))
  .map((e) => e.name)
  .sort()
  .map((name) => {
    const r = JSON.parse(readFileSync(join(DIR, name, 'results.json'), 'utf8'));
    const kinds = r.files.reduce((n, f) => ({ ...n, [f.kind]: (n[f.kind] ?? 0) + 1 }), {});
    const reports = readdirSync(join(DIR, name)).filter((f) => f.endsWith('.html')).sort();
    return `| [${name}](${name}/README.md) | ${r.observedAt} | ${r.files.length} (${Object.entries(kinds).map(([k, v]) => `${v} ${k}`).join(', ')}) | tells ${r.tool.version} | ${reports.map((f) => `[${f}](${name}/${f})`).join(', ')} | \`${r.command}\` |`;
  });

writeFileSync(
  join(DIR, 'INDEX.md'),
  `# Studies

Generated by \`node scripts/studies-index.mjs\`. Each study is a dated run. Figures describe the files in that study on that date and are not an accuracy claim about any detector, including this one.

| study | observed | files | version | rendered reports | reproduce |
|---|---|---|---|---|---|
${rows.join('\n')}
`,
);
console.log(`wrote studies/INDEX.md (${rows.length} study)`);
